### ISSUE TITLE
マニュアル投稿の連続投稿抑止論理を追加

### ISSUE THREAD

**Issue by tsu-nera** [peach-hack/auto-matching#100]
### 要件
悪い人が悪用して30分に一度投稿とかしないようにしたい。

### 仕様
- 3時間に以内に投稿があったら、自動投稿機能を動かさない。

DBのsource_site.post_at に 最終投稿成功時刻が入っているので、この時刻が現在から３時間いないかどうかを判定。

- 3時間という数は、環境変数で変更可能としておく
- ガードしましたということをどうやってUIに表示するかは後で考えるので、今はとりあえずなにもしない。

### 参考

https://github.com/tsu-nera/auto-matching/blob/master/auto-matching-api-rails/app/controllers/api/users/posts/manual_posts_controller.rb

https://github.com/tsu-nera/auto-matching/blob/master/auto-matching-api-rails/app/jobs/manual_post_job.rb

**Comment by tsu-nera** [comment]
もっと改善すると、SourceSite のテーブルに activate_flagというフラグがあるので、これを定期的に監視して３時間経過で落とすような処理をいれたほうがいいが、とても難しいので、アイデアだけにしておいて検討は保留にしよう。

**Comment by tsu-nera** [comment]
UIからも、禁止状態を表示します。表示は #41 で対応します。

**Comment by tsu-nera** [comment]
表示は別件

**Comment by tokidrill** [comment]
実装方法はJob側で判定するように。
詳細は下記。
実行条件判定の検討 #331

**Comment by tokidrill** [comment]
jobの成否、及び抑止のハンドリングについて考えているんですが、
• 抑止されたときはDBに変更を加えたくない
• 成功すればset_successでDB変更を加える
• 失敗すればset_errorでDB変更を加える

という実装になっているので、抑止と判定されたら独自定義の例外をraiseして、rescueした先で抑止のステータスだけNuxt側に投げる、という実装を考えてます。

詳しくは [プルリク](https://github.com/peach-hack/auto-matching/commit/bcb65baf27678233b9ee5cb26e6f6717d0609fb6) をご覧ください。

**Comment by tokidrill** [comment]
祝！初Merge！
