### ISSUE TITLE
開発で得た知見をOutputする方法を考える

### ISSUE THREAD

**Issue by tsu-nera** [peach-hack/auto-matching#167]
就活で自分を売り込むことが目的のプロジェクトなので、知見をアウトプットすることが大事だと気づいた。しかし、がっつり開発しながらだとアウトプットもできないので、開発が一段落したらまとめてアウトプットすることにする。

**Comment by tsu-nera** [comment]
## ネタ一覧

- swaggerを利用してApi Clientコード生成

**Comment by tokidrill** [comment]
> Nuxt.jsとRailsのディレクトリ構造の検討

ココらへんは、モダンなアーキの学習リソースになると思うので、ごく個人的ではありますが期待

**Comment by tsu-nera** [comment]
duplicated
