### ISSUE TITLE
実行条件判定の検討

### ISSUE THREAD

**Issue by tsu-nera** [peach-hack/auto-matching#331]

**Comment by tsu-nera** [comment]
https://github.com/tsu-nera/auto-matching/pull/289#discussion_r251244402

**Comment by tokidrill** [comment]
あり得るステータス
* 成功
* 失敗
* 空白(対象サイトをIDEから利用したことがない)
* 連投防止論理による抑止
    * 抑止された場合はDB上のステータスは変更しない

縦: 最終投稿試行日時　横:DB上であり得るステータス
 
  | 成功 | 失敗 | 空白
-- | -- | -- | --
3時間以内 | ☓ | ○ | ○
3時間以上 | ○ | ○ | ○ 

とりあえずこんな感じですよね？

**Comment by tsu-nera** [comment]
実行条件チェック的な通信を、処理の前に入れるのがいいかもしれない。
- 一括投稿機能
- リアルタイム検索機能

で使う。

チェック項目は、

- Railsサーバが立ち上がっている？
- サイト設定で実行条件が有効になっている？
- 時間制限に引っかかっていない？

**Comment by tokidrill** [comment]
そうか、これなら最後のステータスが失敗のときは最後の投稿時間を評価せずに済むし、「抑止」のステータスを持たせることを考慮しなくても済みますね！
* Railsサーバが立ち上がっているか？
    * APIをコールしてレスがあるかで判定、200のレスポンスorタイムアウトが想定される？
* サイト設定で実行条件が有効になっているか？
    * これは有効になっていないとチェックが入らないようにフロント側で制御されていますが、API側でもチェックするということですよね？
* 時間制限に引っかかっていないか 
    * 今回の発端となった件WIPのプルリクの処理を参考に実装。

これらをクリアしたリクエストだけ、Jobを呼び出すようにする、という認識で間違いないですか？

**Comment by tsu-nera** [comment]
> * Railsサーバが立ち上がっているか？
>   
>   * APIをコールしてレスがあるかで判定、200のレスポンスorタイムアウトが想定される？

どういう挙動か調査が必要です。　
#214 とあわせて検討する必要があります。

> * サイト設定で実行条件が有効になっているか？
>   
>   * これは有効になっていないとチェックが入らないようにフロント側で制御されていますが、API側でもチェックするということですよね？

このチェックはなくてもいいんですが、念のためです。

> * 時間制限に引っかかっていないか
>   
>   * �今回の発端となった件WIPのプルリクの処理を参考に実装。
> 
> これらをクリアしたリクエストだけ、Jobを呼び出すようにする、という認識で間違いないですか？

API Requestを2回に分ける感じをイメージしています。

**Comment by tokidrill** [comment]
> どういう挙動か調査が必要です。　
> #214 とあわせて検討する必要があります。

承知です。

> このチェックはなくてもいいんですが、念のためです。

僕もするべきだと思います。

> API Requestを2回に分ける感じをイメージしています。

僕もそのイメージです。
1. チェックのリクエスト
1. Jobをコールするリクエスト

という感じで、2の方を行うかどうかの判定を追加するってイメージですよね？

**Comment by tsu-nera** [comment]
いったん実行中になってから、投稿抑止に戻すのはいいかも。
なぜなら、一瞬なのだから。

なので、ActionJobのなかで新しいステータスを用意する案が再び急浮上。

**Comment by tsu-nera** [comment]
なんども覆してすみません。

ActiveJobの中で、投稿抑止判定をして、ダメな場合は、"投稿抑止中"というステータスに変更するような方針で検討してくれますか？

こうする理由は、はじめは変更中から投稿抑止に倒すのは違和感があったからですが、試してみたら一瞬なので、問題ないことに気づいたからです。

**Comment by tokidrill** [comment]
* ~~Railsサーバが立ち上がっている？~~
* サイト設定で実行条件が有効になっている？
* 時間制限に引っかかっていない？

その場合、Railsサーバが立ち上がっているかは別の部分で判断するような仕組みでOKですよね？
また、抑止のステータスを返す場合はhistory.updateを呼ばずに、DB上では「成功」のステータスのままで更新しないということでいいでしょうか？

**Comment by tsu-nera** [comment]
> その場合、Railsサーバが立ち上がっているかは別の部分で判断するような仕組みでOKですよね？
はい。

> また、抑止のステータスを返す場合はhistory.updateを呼ばずに、DB上では「成功」のステータスのままで更新しないということでいいでしょうか？
はい、成功のままで。

**Comment by tsu-nera** [comment]
https://github.com/peach-hack/auto-matching/pull/289/

で対応している。重複になるので、こちらは閉じておきます。
