### ISSUE TITLE
[掲示板監視] DB容量制限機能を作成

### ISSUE THREAD

**Issue by tsu-nera** [peach-hack/auto-matching#378]
Heroku PostgreSQLの容量制限が10000レコードなため、定期的に削除することが必要。

定期監視の延長で、Post.countみたいな感じで、Postテーブルのレコード数を数えて多かったら削除する。

**Comment by tsu-nera** [comment]
ごいさんはエクセルスクショ職人になるため、なかなか着手ができないかも。
そしたら、つーねらが引き受けます。

**Comment by tsu-nera** [comment]
https://github.com/peach-hack/auto-matching/blob/master/auto-matching-api-rails/app/controllers/api/users/posts/daily_crawl_controller.rb#L24

定期監視の延長で、このへんがよさそう。

**Comment by Goi666** [comment]
その位置だと **掲示板監視実行コマンド** を叩いても走らなかったです。

**Comment by Goi666** [comment]
ここだとダメなんですかね？

https://github.com/peach-hack/auto-matching/blob/master/auto-matching-api-rails/lib/auto_matching/reader/executor.rb

**Comment by tsu-nera** [comment]
うーん、考えます。

定期監視は、controllerに post requestをなげて動かすので rakeコマンドからは動かさない想定でしたが、テストがしにくいですね。controllerでチェックするべきか、非同期jobでチェックするべきか。

**Comment by tsu-nera** [comment]
Executorだと、一回のジョブで6回（サイト分）動作しちゃいますね。

**Comment by Goi666** [comment]
ちなみに走らない ＝ ログ出力で確認できていない
という意味です。

一応指定位置で "logger.debug("ABC")" や "puts "ABC" "とか試しました。

**Comment by tsu-nera** [comment]
putsでいけるはず。

**Comment by tsu-nera** [comment]
やはりここでお願いします。
https://github.com/peach-hack/auto-matching/issues/378#issuecomment-461824561

理由は、6回処理が動くのは冗長だからです。テストはやりにくいですが、できないことはありませんので、フォローします。

**Comment by tsu-nera** [comment]
Postレコードが7000以上で消す感じで。
Profileは難しいので、あとで考えます。やらないといけないのだけど。
