### ISSUE TITLE
2/23 connecting the dot's 最終打ち合わせ 13:00

### ISSUE THREAD

**Issue by tsu-nera** [peach-hack/auto-matching#436]
## 話すこと

* [x] 進捗の確認
* [x] issue, prの棚卸し
* [x] 今後の開発について
* [ ] 営業拡販作戦の検討 #323 
* [x] リリース発表資料のレビュー
* [x] 個人サーバ環境構築の指南(AWS)
* [ ]  探索的強化テスト

##  開発お疲れさま会

Hacker's Bar

https://hackers.bar/

**Comment by tsu-nera** [comment]
## 今後の開発について

みんな忙しいので、さてどうしよう。

* @tsu-nera 就活
* @tokidrill なおとさんのほう
* @Goi666 基本情報試験、パチンコ、Tinder

**Comment by tsu-nera** [comment]
## 拡販営業活動の検討

* まずはエンジニアのみなさんに活用してもらえるように、ドキュメントを整備する。
* インフラや環境構築手順のノウハウをためていく。品質を高める。
* ぜひ歌舞伎町の女社長に協力してもらいたい。

**Comment by tokidrill** [comment]
* 今後の開発
僕全然コミットできてないので、ちまちまとやっていきたい。
